name: Validate Template

on:
  push:
    branches:
      - main

jobs:
  validate_xml:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Validate XML files
        uses: action-pack/valid-xml@v1
        with:
          path: "templates/"
          file-endings: ".xml"
